### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by LeninaCrowne** [adamkiss/kirby-goat-counter#1]
Hi, I cannot get the plugin to work with my site.
- My page at goatcounter shows : _No data received_
- The Analytics panel on Kirby shows : _There's currently an issue with the Goat Counter where the "access-token → redirect" pattern might be blocked by your browser. You can check the analytics in a new tab instead._ And I can't log in. I've added exception for my site and I disabled the Firefox plugins that could interfere.
![image](https://github.com/adamkiss/kirby-goat-counter/assets/64606118/a15d6dae-5714-4cb0-b97a-ecb8c3c9a77c)

I've put the kirby-goat-counter folder in the site/plugins folder
I've updated config.php and added `<?php snippet('goat-counter'); ?>` in header.php
I'm note sure if I also have to add the snippet in the site/snippets folder and rename it goat-counter (I tried it, doesn't work neither).

Thanks a lot.

**Comment by adamkiss** [comment]
I'll have to check it out and update myself on what's new with Goat Counter, but if the situation around embedding goat counter hasn't changed, I'll probably archive this plugin.

**Comment by adamkiss** [comment]
I'll be archiving this plugin shortly
